language: java
jdk:
  - oraclejdk8
cache:
  directories:
    - $HOME/.m2

before_install:
  - git clone https://github.com/lorislab/travis-configuration.git .scripts

install: .scripts/install.sh
script: .scripts/build.sh
